# Generated by Django 5.2.14 on 2026-06-01 08:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_clause_template_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtractionSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('span_text', models.TextField()),
                ('start_char', models.PositiveIntegerField()),
                ('end_char', models.PositiveIntegerField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('extraction_model', models.CharField(default='rules-engine-v1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_char'],
            },
        ),
        migrations.CreateModel(
            name='TrustTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=300)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='carecategorysubcategory',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='care_domains',
        ),
        migrations.RemoveField(
            model_name='duediligenceprocess',
            name='care_category_main',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='target_care_categories',
        ),
        migrations.RemoveField(
            model_name='duediligenceprocess',
            name='care_category_sub',
        ),
        migrations.RemoveField(
            model_name='caseassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='caseassessment',
            name='due_diligence_process',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='client',
        ),
        migrations.RemoveField(
            model_name='duediligenceprocess',
            name='risk_factors',
        ),
        migrations.AlterModelOptions(
            name='duediligenceprocess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trustaccount',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='workflowstep',
            name='workflow_step_stat_due_ix',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('organization', 'year', 'quarter', 'department')},
        ),
        migrations.RemoveField(
            model_name='duediligenceprocess',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='linked_providers',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='care_type',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='open_slots',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='region',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='wait_days',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='waiting_list_size',
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='status',
            field=models.CharField(choices=[('INTAKE', 'Intake'), ('ASSESSMENT', 'Beoordeling'), ('MATCHING', 'Matching'), ('DECISION', 'Matchbesluit'), ('COMPLETED', 'Afgerond'), ('ON_HOLD', 'In wacht')], default='INTAKE', max_length=20),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='target_completion_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='transaction_type',
            field=models.CharField(choices=[('MERGER', 'Merger'), ('ACQUISITION', 'Acquisition'), ('JOINT_VENTURE', 'Joint Venture'), ('ASSET_PURCHASE', 'Asset Purchase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matter',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='contracts.client'),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10, verbose_name='Urgentie'),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trademarkrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FILED', 'Filed'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='aiextractionspan',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extraction_spans', to='contracts.document'),
        ),
        migrations.AddField(
            model_name='aiextractionspan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extraction_spans', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contracts.trustaccount'),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusttransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.invoice'),
        ),
        migrations.DeleteModel(
            name='CareCategoryMain',
        ),
        migrations.DeleteModel(
            name='CareCategorySubcategory',
        ),
        migrations.DeleteModel(
            name='CaseAssessment',
        ),
        migrations.DeleteModel(
            name='ProviderProfile',
        ),
        migrations.DeleteModel(
            name='RiskFactor',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='linked_cases',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='linked_placements',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='linked_providers',
        ),
        migrations.AddIndex(
            model_name='aiextractionspan',
            index=models.Index(fields=['document', 'label'], name='contracts_a_documen_fcd7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextractionspan',
            index=models.Index(fields=['organization', 'label'], name='contracts_a_organiz_8d51cf_idx'),
        ),
    ]
