# Generated by Django 5.2.14 on 2026-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_ai_extraction_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadline_type',
            field=models.CharField(choices=[('COURT', 'Court Deadline'), ('FILING', 'Filing Deadline'), ('SOL', 'Statute of Limitations'), ('CONTRACT', 'Contract Deadline'), ('REGULATORY', 'Regulatory Deadline'), ('INTERNAL', 'Internal Deadline'), ('CLIENT', 'Client Deadline'), ('RENEWAL', 'Renewal / Termination'), ('PAYMENT', 'Payment Obligation'), ('NDA_EXPIRY', 'NDA Expiry'), ('SLA', 'SLA Obligation'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
