# Generated by Django 5.2.14 on 2026-06-01 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_obligation_deadline_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_required', models.BooleanField(default=False)),
                ('require_approval_above_value', models.DecimalField(blank=True, decimal_places=2, help_text='Contracts above this value require approval', max_digits=14, null=True)),
                ('data_transfer_review_required', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555, help_text='Document retention period (default 7 years)')),
                ('max_api_tokens_per_user', models.PositiveIntegerField(default=5)),
                ('allow_public_sharing', models.BooleanField(default=False)),
                ('ai_features_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='contracts.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_org_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation Policy',
                'verbose_name_plural': 'Organisation Policies',
            },
        ),
        migrations.CreateModel(
            name='ClauseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('LIMITATION_OF_LIABILITY', 'Limitation of Liability'), ('INDEMNIFICATION', 'Indemnification'), ('CONFIDENTIALITY', 'Confidentiality'), ('TERMINATION', 'Termination'), ('GOVERNING_LAW', 'Governing Law'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('DATA_PROTECTION', 'Data Protection'), ('FORCE_MAJEURE', 'Force Majeure'), ('PAYMENT_TERMS', 'Payment Terms'), ('IP_OWNERSHIP', 'IP Ownership'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], max_length=40)),
                ('recommendation_text', models.TextField()),
                ('confidence', models.FloatField(default=0.8, help_text='0.0–1.0 confidence score')),
                ('rationale', models.TextField(blank=True, help_text='Why this clause is recommended')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_clause_recommendations', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_recommendations', to='contracts.contract')),
            ],
            options={
                'ordering': ['-confidence', 'clause_type'],
                'indexes': [models.Index(fields=['contract', 'accepted'], name='cr_contract_accepted_ix')],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title_snapshot', models.CharField(max_length=200)),
                ('status_snapshot', models.CharField(max_length=20)),
                ('content_snapshot', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of content_snapshot', max_length=64)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_versions', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['contract', '-version_number'], name='cv_contract_ver_ix')],
                'unique_together': {('contract', 'version_number')},
            },
        ),
    ]
