# Generated by Django 5.2.15 on 2026-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0055_document_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='saml_accepted_authn_contexts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='saml_mfa_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
