# Generated by Django 5.2.15 on 2026-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0056_saml_mfa_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='delivery_error',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='last_delivery_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
