# Generated by Django 5.2.15 on 2026-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0063_organization_workspace_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('NDA', 'Non-Disclosure Agreement'), ('MSA', 'Master Service Agreement'), ('SOW', 'Statement of Work'), ('SUBCONTRACTOR_SOW', 'Subcontractor SOW Agreement'), ('EMPLOYMENT', 'Employment Agreement'), ('LEASE', 'Lease Agreement'), ('LICENSE', 'License Agreement'), ('VENDOR', 'Vendor Agreement'), ('PARTNERSHIP', 'Partnership Agreement'), ('SETTLEMENT', 'Settlement Agreement'), ('AMENDMENT', 'Amendment'), ('DPA', 'Data Processing Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
