# Generated by Django 5.2.15 on 2026-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0064_add_subcontractor_sow_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('NDA', 'Non-Disclosure Agreement'), ('NON_COMPETE', 'Non-Compete / Non-Solicitation Agreement'), ('MSA', 'Master Service Agreement'), ('SOW', 'Statement of Work'), ('SUBCONTRACTOR_SOW', 'Subcontractor SOW Agreement'), ('CONSULTING', 'Consulting / Independent Contractor Agreement'), ('EMPLOYMENT', 'Employment Agreement'), ('LEASE', 'Lease Agreement'), ('LICENSE', 'License Agreement'), ('TERMS_OF_SERVICE', 'Terms of Service / Terms & Conditions'), ('VENDOR', 'Vendor Agreement'), ('PURCHASE_ORDER', 'Purchase Order'), ('PARTNERSHIP', 'Partnership Agreement'), ('RESELLER', 'Referral / Reseller / Channel Partner Agreement'), ('SETTLEMENT', 'Settlement Agreement'), ('AMENDMENT', 'Amendment'), ('DPA', 'Data Processing Agreement'), ('BAA', 'Business Associate Agreement (BAA)'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
