# Generated by Django 5.2.15 on 2026-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0065_add_more_contract_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('NDA', 'Non-Disclosure Agreement'), ('NON_COMPETE', 'Non-Compete / Non-Solicitation Agreement'), ('MSA', 'Master Service Agreement'), ('SOW', 'Statement of Work'), ('SUBCONTRACTOR_SOW', 'Subcontractor SOW Agreement'), ('CONSULTING', 'Consulting / Independent Contractor Agreement'), ('EMPLOYMENT', 'Employment Agreement'), ('LEASE', 'Lease Agreement'), ('LICENSE', 'License Agreement'), ('TERMS_OF_SERVICE', 'Terms of Service / Terms & Conditions'), ('VENDOR', 'Vendor Agreement'), ('PURCHASE_ORDER', 'Purchase Order'), ('PARTNERSHIP', 'Partnership Agreement'), ('RESELLER', 'Referral / Reseller / Channel Partner Agreement'), ('SETTLEMENT', 'Settlement Agreement'), ('AMENDMENT', 'Amendment'), ('DPA', 'Data Processing Agreement'), ('BAA', 'Business Associate Agreement (BAA)'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['contract_type', 'name'],
            },
        ),
    ]
