# Generated by Django 5.2.15 on 2026-07-08 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0067_seed_contract_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCenterRailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('APPROVALS', 'Approvals'), ('DEADLINES', 'Deadlines'), ('DPA_CONFLICTS', 'DPA / MSA Conflicts'), ('REVIEW_MEMOS', 'Review Memos'), ('RISK', 'Risk'), ('ACTIVITY', 'Activity')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('count', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('action_label', models.CharField(default='Open', max_length=80)),
                ('action_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_center_rail_items', to='contracts.organization')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='cc_rail_org_kind_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CommandCenterSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_center_saved_views_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_center_saved_views', to='contracts.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='cc_saved_view_org_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CommandCenterWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('DPA_CONFLICT', 'DPA / MSA Conflict'), ('APPROVAL', 'Approval'), ('DEADLINE', 'Deadline'), ('LEGAL_TASK', 'Legal Task'), ('RISK', 'Risk'), ('REVIEW_MEMO', 'Review Memo')], max_length=20)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('item_type', models.CharField(blank=True, max_length=60)),
                ('stage', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(choices=[(30, 'Low'), (50, 'Medium'), (70, 'High'), (90, 'Critical')], default=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('action_label', models.CharField(default='Open', max_length=80)),
                ('action_path', models.CharField(blank=True, max_length=500)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('last_source_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.approvalrequest')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.contract')),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.deadline')),
                ('dpa_review_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.dpareviewpack')),
                ('dpa_risk_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.dpariskitem')),
                ('legal_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.legaltask')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_center_work_items', to=settings.AUTH_USER_MODEL)),
                ('risk_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_work_items', to='contracts.risklog')),
            ],
            options={
                'ordering': ['-priority', 'due_at', '-updated_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-priority'], name='cc_work_org_status_pri_ix'), models.Index(fields=['organization', 'source_type', 'source_object_id'], name='cc_work_org_source_ix'), models.Index(fields=['organization', 'due_at'], name='cc_work_org_due_ix'), models.Index(fields=['organization', 'owner', 'status'], name='cc_work_org_owner_ix')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'source_model', 'source_object_id'), name='cc_work_source_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ReviewMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('memo_type', models.CharField(choices=[('DPA_REVIEW', 'DPA Review'), ('RISK_REVIEW', 'Risk Review'), ('APPROVAL', 'Approval'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('body', models.TextField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_memos', to='contracts.contract')),
                ('dpa_review_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_memos', to='contracts.dpareviewpack')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_memos_generated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_memos', to='contracts.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', '-generated_at'], name='review_memo_org_gen_ix'), models.Index(fields=['organization', 'memo_type'], name='review_memo_org_type_ix')],
            },
        ),
    ]
