# Generated by Django 5.2.15 on 2026-07-08 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0069_add_saas_contract_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Matches a Contract.ContractType value, e.g. DPA', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commandcenterworkitem',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_center_work_items', to='contracts.workflow'),
        ),
        migrations.AlterField(
            model_name='commandcenterworkitem',
            name='source_type',
            field=models.CharField(choices=[('CONTRACT', 'Contract'), ('DPA_CONFLICT', 'DPA / MSA Conflict'), ('APPROVAL', 'Approval'), ('DEADLINE', 'Deadline'), ('LEGAL_TASK', 'Legal Task'), ('RISK', 'Risk'), ('REVIEW_MEMO', 'Review Memo'), ('WORKFLOW', 'Workflow')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Contract Owner, Legal, DPO, Finance', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('role_label', models.CharField(blank=True, help_text='Plain-language role description shown in the UI', max_length=100)),
                ('is_conditional', models.BooleanField(default=False)),
                ('condition_note', models.CharField(blank=True, max_length=300)),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_routes', to='contracts.workflowtemplate')),
            ],
            options={
                'ordering': ['workflow_template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_templates', to='contracts.contracttype'),
        ),
        migrations.CreateModel(
            name='DraftDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_documents', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_documents', to='contracts.workflow')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Merge-field token name, e.g. dpo_contact', max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('section', models.CharField(choices=[('BASIC_DETAILS', 'Basic details'), ('COMMERCIAL_TERMS', 'Commercial terms'), ('LEGAL_POSITION', 'Legal position'), ('PRIVACY_QUESTIONS', 'Smart privacy questions')], default='BASIC_DETAILS', max_length=20)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('DATE', 'Date'), ('NUMBER', 'Number'), ('BOOLEAN', 'Yes/No'), ('SELECT', 'Select')], default='TEXT', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choices for SELECT fields')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('maps_to_contract_field', models.CharField(blank=True, help_text='If set, this value is also written onto Contract.<field> on submit (e.g. counterparty, start_date).', max_length=40)),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='contracts.workflowtemplate')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='contracts.fielddefinition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='contracts.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable rule identifier, e.g. cross_border_no_mechanism', max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to='contracts.workflow')),
            ],
            options={
                'ordering': ['-severity', 'detected_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('workflow_template', 'key'), name='fielddef_template_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fieldvalue',
            constraint=models.UniqueConstraint(fields=('workflow', 'field_definition'), name='fieldvalue_workflow_field_uniq'),
        ),
    ]
