# Generated by Django 5.2.15 on 2026-07-08 20:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0071_seed_dpa_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='value',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
