# Generated by Django 5.2.15 on 2026-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0075_seed_msa_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='section',
            field=models.CharField(choices=[('BASIC_DETAILS', 'Basic details'), ('COMMERCIAL_TERMS', 'Commercial terms'), ('SERVICES_SCOPE', 'Services & scope'), ('PRIVACY_DETAILS', 'Privacy details'), ('LEGAL_POSITION', 'Legal position'), ('PRIVACY_QUESTIONS', 'Smart privacy questions'), ('SMART_QUESTIONS', 'AI smart questions')], default='BASIC_DETAILS', max_length=20),
        ),
    ]
