# Generated by Django 5.2.16 on 2026-07-24 22:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0115_exception_correlation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('contract_type', models.CharField(default='NDA', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_workflow_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_workflow_definitions', to='contracts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('launch_rationale', models.CharField(blank=True, default='', max_length=500)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_workflow_instance', to='contracts.contract')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='contracts.workflowdefinition')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_workflow_instances_launched', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_workflow_instances', to='contracts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SignaturePacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('provider_name', models.CharField(blank=True, default='', max_length=80)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=191)),
                ('dispatch_idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_signature_packets', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_signature_packets', to='contracts.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_signature_packets', to='contracts.organization')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_packets', to='contracts.workflowinstance')),
            ],
        ),
        migrations.AddField(
            model_name='approvalrequirement',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, help_text='Canonical workflow instance that opened this requirement, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requirements', to='contracts.workflowinstance'),
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('configuration_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_workflow_versions_created', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.workflowdefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_workflow_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['definition_id', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='contracts.workflowversion'),
        ),
        migrations.CreateModel(
            name='ContractRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provenance_locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_contract_records_archived', to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_contract_record', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_contract_records', to='contracts.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_contract_records', to='contracts.organization')),
                ('signature_packet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_record', to='contracts.signaturepacket')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_records', to='contracts.workflowinstance')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_records', to='contracts.workflowversion')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=191)),
                ('event_type', models.CharField(max_length=80)),
                ('provider_name', models.CharField(blank=True, default='', max_length=80)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_signature_evidence', to='contracts.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='contracts.signaturepacket')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'event_type'], name='canon_sigevidence_org_ix')],
                'constraints': [models.UniqueConstraint(fields=('packet', 'event_id'), name='canonical_sigevidence_packet_event_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['organization', 'contract_type'], name='canonical_wfdef_org_type_ix'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='canonical_wfdef_org_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='signaturepacket',
            index=models.Index(fields=['workflow_instance', 'status'], name='canon_sigpacket_inst_ix'),
        ),
        migrations.AddIndex(
            model_name='signaturepacket',
            index=models.Index(fields=['organization', 'status'], name='canon_sigpacket_org_ix'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['definition', 'state'], name='canon_wfver_def_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version_number'), name='canonical_wfver_definition_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['organization', 'status'], name='canonical_wfinst_org_status_ix'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['workflow_version', 'status'], name='canonical_wfinst_ver_status_ix'),
        ),
        migrations.AddIndex(
            model_name='contractrecord',
            index=models.Index(fields=['organization', 'archived_at'], name='canon_record_org_archive_ix'),
        ),
    ]
